### ISSUE TITLE
i get an error...

### ISSUE THREAD

**Issue by Suya1671** [Reavershark/unity-build#1]
umm i dono whats wrong

log:
/usr/bin/docker run --name dfbaa55c734718542798ba992ee8d4a1073_142bb3 --label 488dfb --workdir /github/workspace --rm -e UNITY_LICENSE -e PROJECT_PATH -e BUILD_NAME -e BUILD_TARGET -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/the-cube-game/the-cube-game":"/github/workspace" 488dfb:aa55c734718542798ba992ee8d4a1073
+ mkdir -p /root/.cache/unity3d
+ mkdir -p /root/.local/share/unity3d/Unity/
+ set +x
+ echo Building for StandaloneWindows64
+ export BUILD_PATH=./Builds/StandaloneWindows64/
+ mkdir -p ./Builds/StandaloneWindows64/
Building for StandaloneWindows64
+ pwd
+ xvfb-run --auto-servernum --server-args=-screen 0 640x480x24 /opt/Unity/Editor/Unity -projectPath /github/workspace/./*** -quit -batchmode -nographics -buildTarget StandaloneWindows64 -customBuildTarget StandaloneWindows64 -customBuildName testbuild -customBuildPath ./Builds/StandaloneWindows64/ -executeMethod BuildScript.PerformBuild -logFile
CreateDirectory '' failed:  (current dir: )
Initiating legacy licensing module
DisplayProgressbar: Unity license
[UnityConnectServicesConfig] config is NOT valid, switching to default
[0125/104138:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Home directory not accessible: Permission denied
[0125/104139:ERROR:sandbox_linux.cc(308)] InitializeSandbox() called with multiple threads in process gpu-process
Cancelling DisplayDialog: Failed to activate/update license. Missing or bad username and password. Please try again using valid credentials or contact support@unity3d.com
This should not be called in batch mode.
 
(Filename: ./Editor/Platform/Linux/EditorUtility.cpp Line: 274)

##[error]Docker run failed with exit code 1

**Comment by jnms-me** [comment]
Oh this wasn't really meant to public. This repo was part of a pull request to unitystation about github actions. I'll look into updating this along with instructions. As for the error, you need a (free) unity license file that was generated with the github actions vm machine details. The second action helps in that. I'll maybe update this tomorrow.

**Comment by Suya1671** [comment]
k thanks ill check it out, also does this work with 2019.3 beta yet?

**Comment by jnms-me** [comment]
It works with all versions from the last 5 or so years.

**Comment by Suya1671** [comment]
and  what snippet is the second action

**Comment by jnms-me** [comment]
I'll just point you to https://github.com/Reavershark/unitystation/tree/develop/.github/workflows for the moment

**Comment by jnms-me** [comment]
Initially i created this as a partial rewrite of https://github.com/webbertakken/unity-actions, but that project has gotten a lot of commits recently. It looks more usable now (was broken at the time and couldn't build to linux/mac/windows).

**Comment by webbertakken** [comment]
@Reavershark thanks!

Feel free to request or contribute any features that you're missing to  https://github.com/webbertakken/unity-actions, but it should be quite stable as many people have started using it.

If you choose to convert to my actions, could you please unpublish this action?

**Comment by jnms-me** [comment]
Done
